[package]
name = "deep-research-orchestrator"
edition.workspace = true
version.workspace = true

[dependencies]
deep-research-agent-tools = { workspace = true }
deep-research-arbiter = { workspace = true }
deep-research-react-agent = { workspace = true }
deep-research-tools = { workspace = true }

serde = { workspace = true, features = ["derive"] }
schemars = { workspace = true }

async-stream = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true, features = ["rt"] }

anyhow = { workspace = true }
