[workspace]
members = ["deep-research-agent-tools", "deep-research-api", "deep-research-arbiter", "deep-research-orchestrator", "deep-research-react-agent", "deep-research-reranker", "deep-research-runner", "deep-research-tools"]

[workspace.package]
edition = "2024"
version = "0.1.0"
license = "Apache-2.0"

[workspace.dependencies]
deep-research-api = { path = "deep-research-api" }
deep-research-agent-tools = { path = "deep-research-agent-tools" }
deep-research-arbiter = { path = "deep-research-arbiter" }
deep-research-orchestrator = { path = "deep-research-orchestrator" }
deep-research-react-agent = { path = "deep-research-react-agent" }
deep-research-reranker = { path = "deep-research-reranker" }
deep-research-runner = { path = "deep-research-runner" }
deep-research-tools = { path = "deep-research-tools" }

genai = "0.6.5"

serde = "1.0.229"
serde_json = "1.0.151"
schemars = "1.2.2"
toml = "1.1.6"

chrono = "0.4.45"

async-trait = "0.1.92"
tokio = "1.53.1"
async-stream = "0.3.6"
futures = "0.3.34"
futures-util = "0.3.34"

actix-web = "4.15.0"
tracing-actix-web = "0.7.25"

anyhow = "1.0.104"

reqwest = "0.13.5"

tracing = "0.1.44"
tracing-subscriber = "0.3.23"

sqlx = "0.9.0"
emvedb = "0.1.0"
htmd = "0.5.5"
text-splitter = "0.33.0"

clap = "4.6.7"

[package]
name = "deep-research-agent"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
deep-research-api = { workspace = true }
deep-research-agent-tools = { workspace = true }
deep-research-arbiter = { workspace = true, features = ["semaphore"] }
deep-research-react-agent = { workspace = true }
deep-research-runner = { workspace = true }
deep-research-tools = { workspace = true }
genai = { workspace = true }
deep-research-orchestrator = { workspace = true }

serde = { workspace = true, features = ["derive"] }
toml = { workspace = true }

anyhow = { workspace = true }

tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }

clap = { workspace = true, features = ["derive"] }
