[workspace]
members = ["deep-research-agent-tools", "deep-research-api", "deep-research-arbiter", "deep-research-orchestrator", "deep-research-react-agent", "deep-research-runner", "deep-research-tools"]

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.dependencies]
deep-research-agent-tools = { path = "deep-research-agent-tools" }
deep-research-arbiter = { path = "deep-research-arbiter" }
deep-research-orchestrator = { path = "deep-research-orchestrator" }
deep-research-react-agent = { path = "deep-research-react-agent" }
deep-research-runner = { path = "deep-research-runner" }
deep-research-tools = { path = "deep-research-tools" }

genai = "0.6.5"

serde = "1.0.229"
serde_json = "1.0.151"
schemars = "1.2.2"

chrono = "0.4.45"

async-trait = "0.1.92"
tokio = "1.53.1"
async-stream = "0.3.6"
futures = "0.3.34"
futures-util = "0.3.34"

actix-web = "4.15.0"

anyhow = "1.0.104"

reqwest = "0.13.5"

[package]
name = "deep-research"
version.workspace = true
edition.workspace = true

[dependencies]
