[package]
name = "deep-research-agent-tools"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
deep-research-react-agent = { workspace = true }
deep-research-tools = { workspace = true }
deep-research-runner = { workspace = true }

schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

async-trait = { workspace = true }

genai = { workspace = true }

anyhow = { workspace = true }
