[package]
name = "deep-research-arbiter"
edition.workspace = true
version.workspace = true

[dependencies]
async-trait = { workspace = true }

anyhow = { workspace = true }

tokio = { workspace = true, features = ["sync"], optional = true }

[features]
semaphore = ["tokio"]

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
