[package]
name = "deep-research-tools"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
deep-research-reranker = { workspace = true }
deep-research-arbiter = { workspace = true }

async-trait = { workspace = true }
anyhow = { workspace = true }

schemars = { workspace = true, features = ["chrono04"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

genai = { workspace = true }

reqwest = { workspace = true, features = ["json", "rustls"] }

chrono = { workspace = true, features = ["serde"] }
tokio = { workspace = true, features = ["net", "time", "rt"] }
tracing = { workspace = true }
encoding_rs = "0.8.35"
mime = "0.3.17"

sqlx = { workspace = true, features = ["sqlite-bundled", "chrono", "runtime-tokio"] }
emvedb = { workspace = true }
htmd = { workspace = true }
text-splitter = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "io-util"] }
