[package]
name = "deep-research-runner"
edition.workspace = true
version.workspace = true

[dependencies]
deep-research-arbiter = { workspace = true }
deep-research-tools = { workspace = true }

genai = { workspace = true }

async-trait = { workspace = true }
async-stream = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }

anyhow = { workspace = true }

